# Create volumes from vars
---
- name: Create File system
  tags: 'volumes'
  become: yes
  filesystem:
    fstype: xfs
    dev: /dev/vdb

- name: Checking folders
  tags: 'volumes'
  become: yes
  stat:
    path: /mystrore
  register: directory_stats

- name: Create directory
  tags: 'volumes'
  become: yes
  file:
    path: /mystrore
    recurse: yes
    state: directory

- name: Mount device
  tags: 'volumes'
  become: yes
  mount:
    path: /mystore
    src: /dev/vdb
    fstype: xfs
    state: mounted

# - name: Creating partetion
#   parted:
#     device: /dev/vdb
#     number: 1
#     state: present

# - name: vgcreate
#   lvg:
#     vg: vgdata
#     pvs: /dev/vdb2

# - name: Creating file system
#   filesystem:
#     fstype: ext4
#     dev: /dev/vdb1

# - name: Mounting the volume
#   mount:
#     name: /storage
#     src: /dev/vdb1
#     fstype: ext4
#     state: mounted