#common vars
availability_zone: melbourne-qh2-uom

#volume
volumes:
  - vol_name: syd-db-volume
    vol_size: 40

# Security groups
security_groups:
  - name: set_ssh
    description: "Adding SSH access to web Server"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - name: set_http
    description: "Adding HTTP access to web Server"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: set_couch
    description: "Opening the port for couch"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5987
    remote_ip_prefix: 0.0.0.0/0

  - name: set_application_ports
    description: "Opening "
    protocol: tcp
    port_range_min: 50000
    port_range_max: 50010
    remote_ip_prefix: 0.0.0.0/0

#instance
instance_name: syd_db_server
instance_image: cb6d0a36-37f4-47c4-8a82-e201bf667211
instance_key_name: webServer
instance_flavor: uom.mse.2c9g

