# install dependencies on the host
---
- name: Gathering facts
  setup:
    gather_subset: all

- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'virtualenv' ,'git', 'python-pip','vim', 'python-setuptools']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest

- name: Install pip3
  become: yes
  apt:
    name: ['python3-pip']
    state: latest

- name: Install flask and flask_auth
  become: yes
  pip:
    name: ['flask', 'flask_httpauth']
    state: latest