- hosts: localhost
  vars_files:
    - host_vars/appServer.yaml
  gather_facts: true
  
  roles:
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    - role: openstack-common
    - role: openstack-volume-snapshot