# show all available Openstack images

# - name: Set docker proxies
#   tags: 'docker'
#   become: yes
#   environment:

- name: Uninstall old docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

- name: Install dependecies for docker
  tags: 'docker'
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'python-setuptools', 'software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add docker apt repository key
  tags: 'docker'
  become: yes
  apt-key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repo and update apt cache
  tags: 'docker'
  beocme: yes
  apt_repository:
    repo: "deb https:// download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_repo_version }}"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  tags: 'docker'
  become: yes
  pip:
    name: ['docker-compose']
    version: 1.22.0
    state: preset