# install dependencies on the host
---
- name: Gathering facts
  setup:
    gather_subset: all

- name: Install dependencies
  become: yes
  apt:
    name: ['virtualenv']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Installing ['nltk','CouchDB', 'tweepy', 'Shapely']
  become: yes
  pip:
    name: ['nltk','CouchDB', 'tweepy', 'Shapely']
    executable: pip3
    state: latest
